name: bitsstack_flutter_app
description: Flutter Application for Android and iOS Devices.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: SF Pro Display
        fonts:
          - asset: assets/fonts/sf-ui-display-black.otf
            weight: 900
          - asset: assets/fonts/sf-ui-display-heavy.otf
            weight: 800
          - asset: assets/fonts/sf-ui-display-bold.otf
            weight: 700
          - asset: assets/fonts/sf-ui-display-semibold.otf
            weight: 600
          - asset: assets/fonts/sf-ui-display-medium.otf
            weight: 500
          - asset: assets/fonts/sf-ui-display-light.otf
            weight: 400
          - asset: assets/fonts/sf-ui-display-thin.otf
            weight: 300
          - asset: assets/fonts/sf-ui-display-ultralight.otf
            weight: 200
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
